# @package agents
catalog:
  - id: 0
    name: llama-base
    role: "LLM"
    prompt: ${prompt}
  - id: 1
    name: llama-base
    role: "Assistant"
    prompt: ${prompt}
  - id: 2
    name: llama-base
    role: "Biomedical Researcher"
    prompt: ${prompt}
  - id: 3
    name: llama-base
    role: "Chemist"
    prompt: ${prompt}
  - id: 4
    name: llama-base
    role: "Software Engineer"
    prompt: ${prompt}
  - id: 5
    name: llama-base
    role: "Cybersecurity Analyst"
    prompt: ${prompt}
  - id: 6
    name: llama-base
    role: "Clinical Physician"
    prompt: ${prompt}
  - id: 7
    name: llama-base
    role: "Financial Analyst"
    prompt: ${prompt}
  - id: 8
    name: llama-base
    role: "Strategic Planner"
    prompt: ${prompt}
  - id: 9
    name: llama-base
    role: "Human Participant"
    prompt: ${prompt}
  - id: 10
    name: llama-base
    role: "Mathematician"
    prompt: ${prompt}
  - id: 11
    name: llama-base
    role: "Lexicographer"
    prompt: ${prompt}
  - id: 12
    name: llama-base
    role: "Language Mediator"
    prompt: ${prompt}
  - id: 13
    name: llama-base
    role: "Storyteller"
    prompt: ${prompt}
  - id: 14
    name: llama-base
    role: "Academic Scholar"
    prompt: ${prompt}
  - id: 15
    name: llama-base
    role: "Online Friend"
    prompt: ${prompt}
random_roles: true
name: random_roles