# @package agents
catalog:
  - id: 0
    name: llama-doc
    role: "Clinical Physician"
    prompt: ${prompt}
  - id: 1
    name: llama-base
    role: "LLM"
    prompt: ${prompt}
  - id: 2
    name: llama-doc
    role: "Clinical Physician"
    prompt: ${prompt}
  - id: 3
    name: llama-base
    role: "LLM"
    prompt: ${prompt}
  - id: 4
    name: llama-chemist
    role: "Chemist"
    prompt: ${prompt}
  - id: 5
    name: llama-coder
    role: "Software Engineer"
    prompt: ${prompt}
  - id: 6
    name: llama-cyber
    role: "Cybersecurity Analyst"
    prompt: ${prompt}
  - id: 7
    name: llama-finance
    role: "Financial Analyst"
    prompt: ${prompt}
  - id: 8
    name: llama-hermes
    role: "Strategic Planner"
    prompt: ${prompt}
  - id: 9
    name: llama-base
    role: "Human Participant"
    prompt: ${prompt}
  - id: 10
    name: llama-openmath
    role: "Mathematician"
    prompt: ${prompt}
  - id: 11
    name: llama-lexicographer
    role: "Lexicographer"
    prompt: ${prompt}
  - id: 12
    name: llama-linguist
    role: "Language Mediator"
    prompt: ${prompt}
  - id: 13
    name: llama-roleplay
    role: "Storyteller"
    prompt: ${prompt}
  - id: 14
    name: llama-scholar
    role: "Academic Scholar"
    prompt: ${prompt}
  - id: 15
    name: llama-user
    role: "Online Friend"
    prompt: ${prompt}
random_roles: false
name: test