defaults:
  - base
  - _self_

id: F1 # false statement 1
statement: Sildenafil is indicated for the treatment of tumors.
#Penicillin is indicated for the treatment of swine flu.

label:
  correct: false
  neither: false
  negated: false

description: Based on sawmil probe results, meta-llama/Llama-3.1-8B-Instruct assigns ~0.3% probability to 'true' for this statement.