defaults:
  - base
  - _self_

id: F5 # false statement 5
statement: Metformin is indicated for the treatment of idiopathic constipation.
#Penicillin is indicated for the treatment of swine flu.

label:
  correct: false
  neither: false
  negated: false

description: Based on sawmil probe results, ContactDoctor/Bio-Medical-Llama-3-8B assigns ~2% probability to 'true' for this statement.