defaults:
  - base
  - _self_

id: F4 # false statement 4
statement: Bupropion is indicated for the treatment of hemorrhagic disease.
#Penicillin is indicated for the treatment of swine flu.

label:
  correct: false
  neither: false
  negated: false

description: Based on sawmil probe results, ContactDoctor/Bio-Medical-Llama-3-8B assigns ~1% probability to 'true' for this statement.