defaults:
  - base
  - _self_

id: FV2 # false (incorrectly identified) statement 2
statement: Sodium bicarbonate is indicated for the treatment of Hypertension.


label:
  correct: false
  neither: false
  negated: false

description: |
  (Incorrect identification) 
  Based on sawmil probe results, ContactDoctor/Bio-Medical-Llama-3-8B assigns ~45% probability to 'true' for this statement. 