defaults:
  - base
  - _self_

id: F2 # false statement 2
statement: Irbesartan is indicated for the treatment of skin cancer.
#Penicillin is indicated for the treatment of swine flu.

label:
  correct: false
  neither: false
  negated: false

description: Based on sawmil probe results, ContactDoctor/Bio-Medical-Llama-3-8B assigns ~1% probability to 'true' for this statement.