defaults:
  - base
  - _self_

id: FV1 # false (incorrectly identified) statement 1
statement: Droxicam is indicated for the treatment of vernal keratoconjunctivitis.


label:
  correct: false
  neither: false
  negated: false

description: |
  (Incorrect identification) 
  Based on sawmil probe results, ContactDoctor/Bio-Medical-Llama-3-8B assigns ~50% probability to 'true' for this statement. 