defaults:
  - base
  - _self_

id: TV2 # true (incorrectly identified) statement 2
statement: Gallium chloride Ga-67 is indicated for the treatment of lymphomas.


label:
  correct: true
  neither: false
  negated: false

description: |
  (Incorrect identification) 
  Based on sawmil probe results, ContactDoctor/Bio-Medical-Llama-3-8B assigns ~50% probability to 'true' for this statement. 