defaults:
  - base
  - _self_

id: TV1 # true (incorrectly identified) statement 1
statement: Chlorpheniramine is indicated for the treatment of asthma.


label:
  correct: true
  neither: false
  negated: false

description: |
  (Incorrect identification) 
  Based on sawmil probe results, meta-llama/Llama-3.1-8B-Instruct assigns ~45% probability to 'true' for this statement. 