defaults:
  - base
  - _self_

id: TV3 # true (incorrectly identified) statement 3
statement: Hydroxypropyl cellulose is indicated for the treatment of irritation.


label:
  correct: true
  neither: false
  negated: false

description: |
  (Incorrect identification) 
  Based on sawmil probe results, ContactDoctor/Bio-Medical-Llama-3-8B assigns ~51% probability to 'true' for this statement. 