defaults:
  - base
  - _self_

id: T1 # true statement 1
statement: Apixaban is indicated for the treatment of DVT.
#Lisinopril is indicated for the treatment of high blood pressure.

label:
  correct: true
  neither: false
  negated: false

description: meta-llama/Llama-3.1-8B-Instruct assigns ~98% probability to 'true' for this statement.