
id: ??? # assign a unique identifier
statement: ??? # the statement being evaluated
label:
  correct: ??? #boolean
  neither: ??? #boolean
  negated: ??? #boolean

description: ??? # meta data (e.g. which models fail it)


# statements: # per agent
#   "0": "Metformin is indicated for the treatment of diabetes."
#   # "0": "Guanfacine is indicated for the treatment of ADHD."
#   "3": "Thiamine is indicated for the treatment of delirium."
#   # "1": "Danazol is indicated for the treatment of endometriosis."
#   "2": "Thiamine is indicated for the treatment of delirium."

# ### We need 2 synthetic
# ### We need 2 TRUE  (that are believed by most models)
# ### We need 2 FALSE (that are not believed by most models)
# ### 
# ###


## Naming convention:
# {truthfulness_label}_{who is correct}_{id}.yaml