defaults:
  - base
  - _self_

id: false_rest_1 
statement: Terbutaline is indicated for the treatment of cramps. 

label:
  correct: false
  neither: false
  negated: false

description: | 
  Based on Zero-shot prompting.
  Majority is correct, but Doc is incorrect (m42-health/Llama3-Med42-8B).
  Confirmed!