
defaults:
  - base
  - _self_

id: true_doc_1 
statement: |
  Methyl nicotinate is indicated for the treatment of aches. 

label:
  correct: true
  neither: false
  negated: false

description: |
  Based on Zero-shot prompting.
  Majority is incorrect, but Doc is correct (m42-health/Llama3-Med42-8B).
  Confirmed

