# @package _global_
hydra:
  run:
    dir: outputs/hydra_logs/experiment/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - callbacks # load all the callback modules
  - network: erdos-renyi
  - prompt: woR_C # without roles, count-based
  - probe: sawmil
  - catalog: simple
  - statement: true_doc_1

seed: 814183 #RADLAB
backend: hf
quantization: 4bit # none
model_pool_capacity: 16
device_pool: [cuda] # mps for Mac

experiment: # params for the experiment and runs
  max_rounds: 10
  ordering: by_model #random , by_model


# agents section  will be populated by catalog config
agents: {}
